dashboard:
  build: ./dashboard

postgres_data:
  image: postgres
  entrypoint: /bin/true
postgres:
  image: postgres
  environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=buildstack
  volumes_from:
    - postgres_data
  ports:
    - "5432:5432"

sonar_data:
  image: sonarqube
  entrypoint: /bin/true
  volumes:
    - ./sonar/sonar.properties:/opt/sonarqube/conf/sonar.properties
sonar:
  image: sonarqube
  environment:
    - SONARQUBE_JDBC_USERNAME=admin
    - SONARQUBE_JDBC_PASSWORD=admin
    - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres/buildstack
  volumes_from:
    - sonar_data
  links:
    - postgres

artifactory_data:
  image: mattgruter/artifactory:3.7.0
  entrypoint: /bin/echo artifactory data
artifactory:
  image: mattgruter/artifactory:3.7.0
  volumes_from:
    - artifactory_data

jenkins_data:
  image: jenkins
  entrypoint: /bin/true
jenkins:
  build: ./jenkins
  volumes_from:
    - jenkins_data
  volumes:
    - ./jenkins/home:/var/jenkins_home
  links:
    - postgres
    - sonar
    - artifactory
  command: --prefix=/jenkins

nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - dashboard
    - sonar
    - artifactory
    - jenkins
